Background
sf::Texture Background::background
Referenced by LoadBackgroundTexture, SetBackgroundSprite.
sf::Sprite Background::background_Sprite
Referenced by renderBackground, SetBackgroundSprite.
Background::Background()
References initBackground.
void Background::initBackground()
References LoadBackgroundTexture, SetBackgroundSprite.
Referenced by Background.
void Background::LoadBackgroundTexture()
References background.
Referenced by initBackground.
void Background::SetBackgroundSprite()
References background, background_Sprite.
Referenced by initBackground.
void Background::renderBackground(sf::RenderTarget &window)
References background_Sprite.
Referenced by main.