Player
sf::Vector2i Player::mouse
Referenced by playerRotate, updateMousePos.
float Player::angle
Referenced by playerRotate.
sf::Texture Player::player_texture
Referenced by Player.
sf::Vector2f Player::player_startPosition
Referenced by Player.
sf::Vector2f Player::player_position
Referenced by playerRotate, updateMousePos.
sf::Vector2f Player::bullet_startPos
sf::Vector2f Player::playerCenter
Referenced by main.
sf::Vector2f Player::mousePosWindow
Referenced by main.
sf::Vector2f Player::aimDir
Referenced by main.
sf::Vector2f Player::aimDirNorm
Referenced by main.
int Player::m_playerHealth
Referenced by LittleEnemy::Attack, Player.
Player::Player()
References m_playerHealth, player_startPosition, player_texture.
void Player::playerMove()
Referenced by playerUpdate.
void Player::updateMousePos(sf::RenderWindow &window)
References mouse, player_position.
Referenced by playerRotate.
void Player::playerRotate(sf::RenderWindow &window)
References angle, mouse, player_position, updateMousePos.
Referenced by playerUpdate.
void Player::playerUpdate(sf::RenderWindow &window)
References playerMove, playerRotate.
Referenced by main.