HighScore
sf::Text HighScore::highscore_Text
Referenced by HighScore, renderHighscore, showText, updateHighScore.
sf::Font HighScore::highscore_Font
Referenced by HighScore.
std::ostringstream HighScore::ssHighScore
Referenced by showText, updateHighScore.
int HighScore::m_highscore
Referenced by getHighscore, loadHighscore, saveHighScore, setHighscore.
HighScore::HighScore()
References highscore_Font, highscore_Text, loadHighscore, showText.
HighScore::~HighScore()
void HighScore::updateHighScore(Score &obj)
References getHighscore, Score::getScore, highscore_Text, setHighscore, ssHighScore.
Referenced by main.
void HighScore::renderHighscore(sf::RenderTarget &window)
References highscore_Text.
Referenced by main.
int HighScore::getHighscore()
References m_highscore.
Referenced by showText, updateHighScore.
int HighScore::setHighscore(Score &obj)
References Score::getScore, m_highscore.
Referenced by updateHighScore.
void HighScore::loadHighscore()
References m_highscore.
Referenced by HighScore.
void HighScore::saveHighScore(Score &obj)
References m_highscore.
Referenced by main.
void HighScore::showText()
References getHighscore, highscore_Text, ssHighScore.
Referenced by HighScore.