Score
sf::Text Score::score_Text
Referenced by pointsRender, Score, updateText.
int Score::value
Referenced by addPoints, getScore, setValue, updateText.
sf::Font Score::score_Font
Referenced by Score.
std::ostringstream Score::ssScore
Referenced by updateText.
int Score::m_addValue
Referenced by addPoints, setaddPoint.
Score::Score()
References score_Font, score_Text, updateText.
void Score::updateText()
References score_Text, ssScore, value.
Referenced by BigEnemy::killedZombie, LittleEnemy::killedZombie, Score.
void Score::setValue(int n)
References value.
Referenced by main.
void Score::pointsRender(sf::RenderWindow &window)
References score_Text.
Referenced by main.
int Score::getScore()
References value.
Referenced by HighScore::setHighscore, HighScore::updateHighScore.
void Score::setaddPoint(float n)
References m_addValue.
Referenced by BigEnemy::killedZombie, LittleEnemy::killedZombie, main.
void Score::addPoints()
References m_addValue, value.
Referenced by BigEnemy::killedZombie, LittleEnemy::killedZombie.