Game
sf::RenderWindow* Game::window
Referenced by initVariables, initWindow, pollEvents, render, renderEnemies, running, spawnEnemy, updateMousePosition, ~Game.
sf::Event Game::ev
Referenced by pollEvents.
sf::VideoMode Game::videMode
Referenced by initWindow.
sf::Vector2i Game::mousePosWindow
Referenced by updateMousePosition.
sf::Vector2f Game::mousePosView
Referenced by updateMousePosition.
int Game::points
Referenced by initVariables.
float Game::enemySpawnTimer
Referenced by initVariables, updateEnemies.
float Game::enemySpawnTimerMax
Referenced by initVariables, updateEnemies.
int Game::maxEnemies
Referenced by initVariables, updateEnemies.
sf::RectangleShape Game::enemy
Referenced by initEnemies, render, spawnEnemy.
sf::Texture Game::playerTexture
Referenced by initPlayer.
std::vector<sf::RectangleShape> Game::enemies
Referenced by renderEnemies, spawnEnemy, updateEnemies.
std::vector<std::unique_ptr<Player> > Game::players1
void Game::initVariables()
References enemySpawnTimer, enemySpawnTimerMax, maxEnemies, points, window.
Referenced by Game.
void Game::initWindow()
References videMode, window.
Referenced by Game.
void Game::initEnemies()
References enemy.
Referenced by Game.
void Game::initPlayer()
References playerTexture.
Referenced by Game.
Game::Game()
References initEnemies, initPlayer, initVariables, initWindow.
Game::~Game()
References window.
const bool Game::running() const
References window.
Referenced by main.
void Game::pollEvents()
References ev, window.
Referenced by update.
void Game::spawnEnemy()
References enemies, enemy, window.
Referenced by updateEnemies.
void Game::updateMousePosition()
References mousePosView, mousePosWindow, window.
Referenced by update.
void Game::updateEnemies()
References enemies, enemySpawnTimer, enemySpawnTimerMax, maxEnemies, spawnEnemy.
Referenced by update.
void Game::update()
References pollEvents, updateEnemies, updateMousePosition.
Referenced by main.
void Game::renderEnemies()
References enemies, window.
Referenced by render.
void Game::renderPlayer()
void Game::render()
References enemy, renderEnemies, window.
Referenced by main.